### ISSUE TITLE
Error on setup: Unable to locate package flask

### ISSUE THREAD

**Issue by mrjones-plip** [NegativeK/picamserver#34]
I had been using the `apt` packages I'd installed a while ago, but I wanted to start clean, so I uninstalled all that (`sudo apt remove -y git screen python3-picamera2 python3-dotenv`) and then went to `develop` [branch](https://github.com/NegativeK/picamserver/tree/develop) and ran `apt update` and then ran the install command:

```
root@picam:~# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.

root@picam:~# sudo apt install -y flask git screen python3-picamera2 python3-dotenv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package flask
```

here's my version:

```
root@picam:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

root@picam:~# cat /etc/debian_version
12.8

root@picam:~# uname -m
aarch64
```

**Comment by NegativeK** [comment]
Debian prepends Python package names with python3-. I should've written `python3-flask`.

README.md is updated in develop with 0ade0a8 ; please recheck when you have a moment.

**Comment by mrjones-plip** [comment]
Rad! I'd tried `apt install python-flask` but should have noted the `python3-*` prefix in the other command.   

I'm mid grand re-install (takes >10min), but I'll confirm when that's done - I'm sure it'll be fine.  I'll close this once I confirm!

**Comment by mrjones-plip** [comment]
(and baller YOLO commit to `develop` ; )

**Comment by mrjones-plip** [comment]
0ade0a8 worked!
